### ISSUE TITLE
How to add more than 2 numbers in an arithmatic operation ?

### ISSUE THREAD

**Issue by rsoorajs** [rsoorajs/Java-Calculator#2]
I wrote my Java Calculator using Swing function. Just created its base model and made basic arithmetic functions working. now I got stuck into one problem. Addition, subtraction, division and multiplication everything is working. But the problem is I cant do any operations more than two numbers at a time, Like if I want to subtract 5-4-2,it doesn't working. 5-4 is working, after the result i have again press - 2 again to make it work. Somehow I solved that in Addition but the other three operators are not working yet. Can anyone tell me a way to add at least Five numbers at a time to do mathematical operations ?

**Comment by ghost** [comment]
Are you sure about this I tested your program, I added 1 + 3 + 2 and after I pressed = it showed 6, which is correct, although I did spot some other problems.

**Comment by rsoorajs** [comment]
> Are you sure about this I tested your program, I added 1 + 3 + 2 and after I pressed = it showed 6, which is correct, although I did spot some other problems.

I solved addition.but other three operators are not working

**Comment by rsoorajs** [comment]
> Are you sure about this I tested your program, I added 1 + 3 + 2 and after I pressed = it showed 6, which is correct, although I did spot some other problems.

can you give me a sample pull request to know the change ,or sugest me an idea to make things work ?

**Comment by ghost** [comment]
I did not make any change to the code, besides configuring the files a bit, since it would not just run. I added it a Main.java (which is required in order for the program to run) and a package ( I don't know about this but IntelliJ Idea forced me to )
